services:
  web:
    image: reportingauto:1.0
    command: gunicorn -w 2 -k gevent --bind 0.0.0.0:8000 reportingauto.wsgi:application
    env_file:
      - .env.test
    ports:
      - "8000:8000"
    depends_on:
      - db
      - broker
      - selenium
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles


  celery_worker:
    image: reportingauto:1.0
    command: celery -A reportingauto worker -l INFO
    env_file:
      - .env.test
    depends_on:
      - web
      - broker
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles

  celery_beat:
    image: reportingauto:1.0
    command: celery -A reportingauto beat -l INFO
    env_file:
      - .env.test
    depends_on:
      - web
      - broker
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/

    env_file:
      - .env.prod.db

  broker:
    image: redis:7.2.5

  nginx:
    image: nginx_reporting:1.0

    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 8443:80
    depends_on:
      - web
  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
    command: >
      bash -c 'SE_OPTS="--enable-managed-downloads true" /opt/bin/entry_point.sh'







volumes:
  postgres_data:
  static_volume:
  media_volume: