# Generated by Django 5.0.3 on 2024-03-20 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FichierCSV',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('date_import', models.DateField(auto_now=True)),
                ('contenu', models.FileField(upload_to='csv_files')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FichierCSV',
                'ordering': ['-date_import'],
            },
        ),
        migrations.CreateModel(
            name='MachineVM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('nom_machine', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=100)),
                ('os', models.CharField(max_length=255)),
                ('critical', models.IntegerField()),
                ('important', models.IntegerField()),
                ('moderate', models.IntegerField()),
                ('low', models.IntegerField()),
                ('fichier_csv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.fichiercsv')),
            ],
            options={
                'verbose_name': 'Inventaire',
                'ordering': ['-nom_machine'],
            },
        ),
    ]
