# Generated by Django 5.0.3 on 2024-04-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinevm',
            name='date_import',
            field=models.DateField(auto_now=True),
        ),
    ]
