# Generated by Django 5.0.3 on 2024-04-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_machinevm_modeluuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinevm',
            name='group',
            field=models.CharField(default='NS', max_length=100),
        ),
    ]
