# Generated by Django 5.0.3 on 2024-03-20 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_alter_fichiercsv_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinevm',
            name='fichier_csv',
        ),
    ]
