# Generated by Django 5.0.3 on 2024-04-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_alter_machinevm_date_import'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinevm',
            name='critical',
            field=models.IntegerField(null=True),
        ),
    ]
