# Generated by Django 5.0.6 on 2024-05-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_alter_machinevm_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unsupported_versions', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
