# Generated by Django 5.0.3 on 2024-04-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_alter_machinevm_critical'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradmin',
            name='give_access',
            field=models.BooleanField(default=False),
        ),
    ]
