# Generated by Django 5.0.3 on 2024-03-21 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_remove_machinevm_fichier_csv'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinevm',
            name='fichier_csv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.fichiercsv'),
        ),
        migrations.AlterField(
            model_name='fichiercsv',
            name='contenu',
            field=models.FileField(upload_to='csv_files/'),
        ),
    ]
