# Generated by Django 5.0.6 on 2024-05-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0004_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigVersionHS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unsupported_versions', models.CharField(default='', max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Config',
        ),
    ]
