# Generated by Django 5.0.3 on 2024-03-28 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0005_remove_machinevm_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinevm',
            name='fichier_csv',
        ),
    ]
