# Generated by Django 5.0.3 on 2024-03-28 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0006_remove_machinevm_fichier_csv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinevm',
            name='ip',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='machinevm',
            name='nom_machine',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
