# Generated by Django 5.0.3 on 2024-03-28 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0007_alter_machinevm_ip_alter_machinevm_nom_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichiercsv',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
