# Generated by Django 5.0.6 on 2024-06-01 08:50

import django.core.validators
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0007_alter_machinevm_critical_alter_machinevm_important_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalConfigVersionHS',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('unsupported_versions', models.CharField(default='', max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical config version hs',
                'verbose_name_plural': 'historical config version hss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMachineVM',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('modeluuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('nom_machine', models.CharField(db_index=True, max_length=255)),
                ('date_import', models.DateField(blank=True, editable=False)),
                ('ip', models.CharField(db_index=True, max_length=255)),
                ('group', models.CharField(default='NS', max_length=100)),
                ('os', models.CharField(max_length=255)),
                ('critical', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('important', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('moderate', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('low', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Inventaire',
                'verbose_name_plural': 'historical Inventaires',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
