# Generated by Django 5.0.3 on 2024-04-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0009_machinevm_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinevm',
            name='date_import',
            field=models.DateField(auto_now=True),
        ),
    ]
