# Generated by Django 5.0.6 on 2024-06-04 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0009_alter_configversionhs_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmachinevm',
            name='import_month',
        ),
        migrations.RemoveField(
            model_name='historicalmachinevm',
            name='import_year',
        ),
        migrations.RemoveField(
            model_name='machinevm',
            name='import_month',
        ),
        migrations.RemoveField(
            model_name='machinevm',
            name='import_year',
        ),
    ]
