# Generated by Django 5.0.6 on 2024-06-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0010_remove_historicalmachinevm_import_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmachinevm',
            name='import_month',
            field=models.CharField(default='06', editable=False, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalmachinevm',
            name='import_year',
            field=models.CharField(default='2024', editable=False, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machinevm',
            name='import_month',
            field=models.CharField(default='06', editable=False, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machinevm',
            name='import_year',
            field=models.CharField(default='2024', editable=False, max_length=4),
            preserve_default=False,
        ),
    ]
