# Generated by Django 5.0.6 on 2024-06-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0011_historicalmachinevm_import_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmachinevm',
            name='ip',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalmachinevm',
            name='nom_machine',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='machinevm',
            name='ip',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='machinevm',
            name='nom_machine',
            field=models.CharField(max_length=255),
        ),
    ]
