# Generated by Django 5.0.6 on 2024-06-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0013_alter_historicalmachinevm_import_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmachinevm',
            name='nom_machine',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='machinevm',
            name='nom_machine',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
