# Generated by Django 5.0.6 on 2024-07-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0015_alter_historicalmachinevm_nom_machine_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VMPatchLastUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Update_patchs',
            },
        ),
    ]
